# Recursive
# https://github.com/helm/helm/issues/2247
# https://github.com/Noksa/helm-resolve-deps
  # Default values for cert-manager-init.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
global:
  certificate:
    # -- Name of the certificate and webhook |
    appName: "compcrdwebhook"

oda-crds:
  enabled: true

canvas-namespaces:
  enabled: true
  certManagerNamespace: cert-manager
  componentNamespace: components
  istio:
    # --  Add Istion instrumentation label to the components namespace
    labelEnabledComponent: true

cert-manager-init:
  nameOverride: ""
  fullnameOverride: ""
  namespace: canvas
  # The certificate has a default duration of 90d. It rotates automatically, but the the server using it doesn't handle that rotation
  # https://github.com/tmforum-oda/oda-canvas-charts/issues/38
  #
  # -- Duration of the certificates generate for the webhook in hours |
  certificateDuration: 21600h
  #Cert manager get a lease  object on kube-system namespace to elect leader.
  #The time to wait for a leader is 60s.
  #The lease can survive among installations, so cainjectot can waits up to 60s to become leader
  #If cainjector is not fully initialized we can find the following error
  #  cert-manager-init/templates/issuer.yaml failed: Internal error occurred:
  #  failed calling webhook "webhook.cert-manager.io": failed to call webhook:
  #  Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": x509: certificate signed by unknown authority
  # In seconds
  # -- Time to wait CertManager to be ready to prevent issuer creation errors
  leaseWaitTimeonStartup: 80

  cert-manager:
    enabled: true
    installCRDs: true
    namespace: cert-manager

keycloak:
  enabled: true
  image:
    tag: 20.0.5-debian-11-r2
  auth:
    adminUser: "admin"
    adminPassword: "adpass"
  postgresql:
    enabled: true
    image:
      tag: 15.2.0-debian-11-r31
    auth:
      username: "keycloak"
      password: "keycloakdbuser"
      database: "keycloak"
  # -- Since keycloak 17+, default to / but the controllers work with older versions
  httpRelativePath: "/auth/"
  #proxy: edge
  #tls:
  #  enabled: true
  #  autoGenerated: true
  #extraEnvVars:
  #  - name: PROXY_ADDRESS_FORWARDING
  #    value: "true"
  ##
  # -- Keycloak LoadBalancer and Headless ClusterIp service port
  service:
    ports: &portKeycloak
      http: 8083
  # -- Keycloak HTTP container port
  containerPorts: *portKeycloak

  # -- Create a myrealm realm with a seccon user
  keycloakConfigCli:
    enabled: true
    image:
      tag: 5.5.0-debian-11-r35
    backoffLimit: 1
    command: [ "java", "-jar", "/opt/keycloak-config-cli.jar" ]
    configuration:
      myrealm.json: |
        {
          "enabled": true,
          "realm": "myrealm",
          "users": [
            {
            "username": "seccon",
            "email": "seccon@oda.io",
            "enabled": true,
            "firstName": "Security",
            "lastName": "User"
            }
           ]
        }

  ingress:
    enabled: false
    ingressClassName: "traefik"
    hosts:
      - name: keycloak.local
        path: /
        tls: false

controller:
  deployment:
    controllerName: oda-controller-ingress
    ##compconImage: tmforumodacanvas/component-istio-controller:0.4.0 
    compconImage: mtr.devops.telekom.de/magenta_canvas/public:component-istio-controller-0.4.1-sman 
    imagePullPolicy: IfNotPresent
    istioGateway: true
    secconImage: tmforumodacanvas/security-listener:0.7.0
    monitoredNamespaces: 'components'           # comma separated list of namespaces
    ingressClass:
      enabled: false
      name: nginx
    keycloak: *portKeycloak
    dataDog:
      enabled: true
  #We reuse the admin user created on keycloak installation
  credentials:
    user: admin
    pass: adpass
  configmap:
    kcrealm: myrealm
    # -- Log level [python] (https://docs.python.org/3/library/logging.html
    loglevel: '20'
    
dependentapi-simple-operator:
  enabled: true
  image: mtr.devops.telekom.de/magenta_canvas/public:dependentapi-simple-operator-0.1.0
  imagePullPolicy: Always
  loglevel: '20'

secretsmanagement-operator:
  image: mtr.devops.telekom.de/magenta_canvas/public:secretsmanagement-operator-0.1.0-rc
  imagePullPolicy: Always
  sidecarImage: "mtr.devops.telekom.de/magenta_canvas/public:secretsmanagement-sidecar-0.1.0-rc"
  # TODO: add TLS to canvas-vault-hc
  vault_addr: "http://canvas-vault-hc.canvas-vault.svc.cluster.local:8200"
  auth_path: "jwt-k8s-sman"
  policy_name_tpl: "sman-{0}-policy"
  login_role_tpl: "sman-{0}-role"
  # the secrets mount tempalte can be used to generate cluster specific key-value stores.
  # component-name + namespace might not be unique in a multi-cluster setup sharing one Canvas-Vault 
  secrets_mount_tpl: "kv-{0}"
  secrets_base_path_tpl: "sidecar"
  # audience can be queried with 
  #   kubectl get --raw /.well-known/openid-configuration | jq -r '.issuer'
  #audience: "https://kubernetes.default.svc.cluster.local"
  audience: "https://container.googleapis.com/v1/projects/tmforum-oda-component-cluster/locations/europe-west3/clusters/ihc-dt"
  # INFO=20, DEBUG=10
  logLevel: 20

webhooks:
  image: tmforumodacanvas/compcrdwebhook:0.6.2 
