---
# create http api gw
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: API
metadata:
  name: "eks-01-api"
  namespace: components
spec:
  name: "eks-01"
  protocolType: HTTP
---
# stage
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Stage
metadata:
  name: "default-stage"
  namespace: components
spec:
  apiRef:
    from:
      name: "eks-01-api"
  stageName: "$default"
  autoDeploy: true
  description: "auto deployed stage for eks-01"
---
# route-key used in path
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Route
metadata:
  name: "ack-route-vpclink"
  namespace: components
spec:
  apiRef:
    from:
      name: "eks-01-api"
  routeKey: "ANY /{proxy+}"
  targetRef:
    from:
      name: "vpc-integration"
---
# hook with route. this one uses a public http site as backend
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  name: "vpc-integration"
  namespace: components
spec:
  apiRef:
    from:
      name: "eks-01-api"
  integrationType: HTTP_PROXY
  integrationURI: "arn:aws:elasticloadbalancing:us-west-2:905418332144:listener/net/k8s-istioing-istioing-f1b3a8e7f5/fc18606a4f4709b1/538aef110bd2df8b"
  integrationMethod: ANY
  payloadFormatVersion: "1.0"
  connectionID: "04myi9" # api_gatewayv2_vpc_link_id in terraform output
  connectionType: "VPC_LINK"