---
# create http api gw
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: API
metadata:
  name: "canvas-api-gateay"
  namespace: components
spec:
  name: "canvas-api-gateay"
  protocolType: HTTP
---
# stage
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Stage
metadata:
  name: "default-stage"
  namespace: components
spec:
  apiRef:
    from:
      name: "canvas-api-gateay"
  stageName: "$default"
  autoDeploy: true
  description: "auto deployed stage for canvas-api-gateay"
---
# route-key used in path
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Route
metadata:
  name: "ack-route-vpclink"
  namespace: components
spec:
  apiRef:
    from:
      name: "canvas-api-gateay"
  routeKey: "ANY /{proxy+}"
  targetRef:
    from:
      name: "vpc-integration"
---
# hook with route. this one uses a public http site as backend
apiVersion: apigatewayv2.services.k8s.aws/v1alpha1
kind: Integration
metadata:
  name: "vpc-integration"
  namespace: components
spec:
  apiRef:
    from:
      name: "canvas-api-gateay"
  integrationType: HTTP_PROXY
  integrationURI: "arn:aws:elasticloadbalancing:us-west-2:905418332144:listener/net/k8s-istioing-istioing-0fd6c42858/de98af0d95abb30b/51d004e3bd7f9b10"
  integrationMethod: ANY
  payloadFormatVersion: "1.0"
  connectionID: "b6oxrx" # api_gatewayv2_vpc_link_id in terraform output
  connectionType: "VPC_LINK"