apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-component-operator-configmap
  labels:
    {{- include "component-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  LOGGING: {{ .Values.configmap.loglevel | quote }}
  KEYCLOAK_BASE: "http://{{ .Release.Name }}-keycloak-headless.{{ .Release.Namespace }}:{{ .Values.deployment.keycloak.http}}/auth"
  KEYCLOAK_REALM: {{ .Values.configmap.kcrealm }}
  COMPONENT_NAMESPACE: {{.Values.deployment.monitoredNamespaces}}
  {{- if .Values.deployment.ingressClass.enabled }}
