# This is a CustomResourceDefinition for DependentAPIs.
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "dependentapis.oda.tmforum.org"
  annotations:
    cert-manager.io/inject-ca-from:  {{ printf "%s/%s" .Release.Namespace .Values.global.certificate.appName  }}
spec:
  group: "oda.tmforum.org"
  scope: "Namespaced"
  names:
    plural: "dependentapis"
    singular: "dependentapi"
    kind: "DependentAPI"
  versions:
  - name: "v1beta3"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              name:
                type: string
                description: Name of the API that this component is dependent on
              specification:
                type: string
                format: url
                description: url to the specification of the API. e.g. url to the swagger file
              apitype:
                type: string
                enum:
                - openapi
                description: The type of API specification. Currently only OpenAPI (swagger) is supported.
              resources:
                type: array
                items:
                  type: object
                description: Resources is an optional list of resources that are consumed by the API.
              required:
                type: boolean
                description: Required is a flag that indicates whether the API is required or not.
            required:
            - name
            - apitype
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: API_endpoint
      type: string
      description: API endpoint Url
      jsonPath: .status.dependentAPIStatus.url
    - name: API_ready
      type: string
      description: API configuration is ready - e.g. gateway configuration
      jsonPath: .status.implementation.ready
