global:
  certificate:
    # -- Name of the certificate and webhook |
    appName: "compcrdwebhook"


certManagerNamespace: cert-manager
componentNamespace: components
istio:
  labelEnabledComponent: true