global:
  certificate:
    # -- Name of the certificate and webhook |
    appName: "compcrdwebhook"
# Declare variables to be passed into your templates.

image: tmforumodacanvas/compcrdwebhook:0.5.1

