deployment:
  controllerName: oda-controller-ingress
  #compconImage: tmforumodacanvas/component-istio-controller:0.4.0
  compconImage: mtr.devops.telekom.de/magenta_canvas/public:component-istio-controller-0.4.1
  compconImagePullPolicy: IfNotPresent
  istioGateway: true
  secconImage: tmforumodacanvas/security-listener:0.6.0
  monitoredNamespaces: 'components'           # comma separated list of namespaces
  ingressClass:
    enabled: false
    name: nginx
  keycloak:
    port: 8080
#We reuse the admin user created on keycloak instalation
credentials:
  user: admin
  pass: adpass
configmap:
  #kcbase: http://canvas-keycloak:8088/auth # trying to parameterise this in the configmap
  kcrealm: myrealm
  loglevel: '20'
