vault_addr: "http://canvas-vault-hc.canvas-vault.svc.cluster.local:8200"

auth_path: "jwt-k8s-cv"

policy_name_tpl: "cv-{0}-policy"
login_role_tpl: "cv-{0}-role"
secrets_mount_tpl: "kv-{0}"
secrets_base_path_tpl: "sidecar"

# audience can be queried with 
#   kubectl get --raw /.well-known/openid-configuration | jq -r '.issuer'
audience: "https://kubernetes.default.svc.cluster.local"
#audience: "https://container.googleapis.com/v1/projects/tmforum-oda-component-cluster/locations/europe-west3/clusters/ihc-dt"

logLevel: 20
