image: mtr.devops.telekom.de/magenta_canvas/public:secretsmanagement-operator-0.1.0-rc
imagePullPolicy: Always
sidecarImage: "mtr.devops.telekom.de/magenta_canvas/public:secretsmanagement-sidecar-0.1.0-rc"
# TODO: add TLS to canvas-vault-hc
vault_addr: "http://canvas-vault-hc.canvas-vault.svc.cluster.local:8200"
auth_path: "jwt-k8s-sman"
# the tempaltes can be used to generate cluster specific key-value stores.
# here sman is used as a unique prefix to all created server side resources
# component-name + namespace might not be unique in a multi-cluster setup sharing one Canvas-Vault 
secrets_mount_tpl: "kv-sman/{0}"
policy_name_tpl: "sman-{0}-policy"
login_role_tpl: "sman-{0}-role"
secrets_base_path_tpl: "sidecar"
# audience can be queried with 
#   kubectl get --raw /.well-known/openid-configuration | jq -r '.issuer'
#audience: "https://kubernetes.default.svc.cluster.local"
audience: "https://container.googleapis.com/v1/projects/tmforum-oda-component-cluster/locations/europe-west3/clusters/ihc-dt"
# INFO=20, DEBUG=10
logLevel: 20
