apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "publishedNotifications.oda.tmforum.org"
spec:
  group: "oda.tmforum.org"
  scope: "Namespaced"
  names:
    plural: "subscribedNotifications"
    singular: "subscribedNotification"
    kind: "subscribedNotification"
  versions: 
  - name: "v1alpha1"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    deprecated: false
    schema:
      openAPIV3Schema:
        type: object
        required: ["spec"]
        properties:
          spec:
            type: object                
            x-kubernetes-preserve-unknown-fields: true    
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true    
    additionalPrinterColumns:
    - name: Notified_entity
      type: string
      description: entity t
      jsonPath: .status.apiStatus.entity    
    - name: Implementation_ready
      type: string
      description: API implementation is ready - has passed startup probe checks
      jsonPath: .status.implementation.ready      