apiVersion: oda.tmforum.org/v1beta3
kind: Component
metadata:
  annotations:
    kopf.zalando.org/last-handled-configuration: |
      {"spec":{"coreFunction":{"dependentAPIs":[{"apitype":"openapi","name":"party","specification":"https://open-api.tmforum.org/TMF632-Party-v4.0.0.swagger.json"}],"exposedAPIs":[{"apitype":"openapi","developerUI":"/demo-a-productcatalog/tmf-api/productCatalogManagement/v4/docs","implementation":"demo-a-prodcatapi","name":"productcatalogmanagement","path":"/demo-a-productcatalog/tmf-api/productCatalogManagement/v4","port":8080,"specification":["https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json"]}]},"description":"Simple Product Catalog ODA-Component from Open-API reference implementation.","eventNotification":{"publishedEvents":[],"subscribedEvents":[]},"functionalBlock":"CoreCommerce","id":"TMFC001","maintainers":[{"email":"lester.thomas@vodafone.com","name":"Lester Thomas"}],"managementFunction":{"exposedAPIs":[{"apitype":"prometheus","implementation":"demo-a-productcatalog-sm","name":"metrics","path":"/demo-a-productcatalog/metrics","port":4000}]},"name":"ProductCatalogManagement","owners":[{"email":"lester.thomas@vodafone.com","name":"Lester Thomas"}],"publicationDate":"2023-08-18T00:00:00.000Z","securityFunction":{"componentVault":{"podSelector":{"name":"demo-a-*","namespace":"components","serviceaccount":"default"},"sideCar":{"port":5000},"type":"sideCar"},"controllerRole":"Admin","exposedAPIs":[{"apitype":"openapi","developerUI":"/demo-a-productcatalog/tmf-api/partyRoleManagement/v4/docs","implementation":"demo-a-partyroleapi","name":"partyrole","path":"/demo-a-productcatalog/tmf-api/partyRoleManagement/v4","port":8080,"specification":["https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json"]}]},"status":"specified","version":"0.0.1"},"metadata":{"labels":{"app.kubernetes.io/managed-by":"Helm","oda.tmforum.org/componentName":"demo-a-productcatalog"},"annotations":{"meta.helm.sh/release-name":"demo-a","meta.helm.sh/release-namespace":"components"}},"status":{"coreAPIs":[{"developerUI":"http://34.159.217.74/demo-a-productcatalog/tmf-api/productCatalogManagement/v4/docs","implementation":"demo-a-prodcatapi","ip":"34.159.217.74","name":"demo-a-productcatalog-productcatalogmanagement","path":"/demo-a-productcatalog/tmf-api/productCatalogManagement/v4","port":8080,"ready":true,"uid":"3be7df95-4f7a-45d6-a691-9147bacc644c","url":"http://34.159.217.74/demo-a-productcatalog/tmf-api/productCatalogManagement/v4"}],"managementAPIs":[{"name":"demo-a-productcatalog-metrics","ready":false,"uid":"b0481e80-1454-4c51-baba-8d846b5e4fee"}],"publishedEvents":[],"securityAPIs":[{"developerUI":"http://34.159.217.74/demo-a-productcatalog/tmf-api/partyRoleManagement/v4/docs","implementation":"demo-a-partyroleapi","ip":"34.159.217.74","name":"demo-a-productcatalog-partyrole","path":"/demo-a-productcatalog/tmf-api/partyRoleManagement/v4","port":8080,"uid":"5c04002e-55a0-4a66-9d41-109cee0cc714","url":"http://34.159.217.74/demo-a-productcatalog/tmf-api/partyRoleManagement/v4"}],"securityComponentVault":[[[{"name":"demo-a-productcatalog","ready":false,"uid":"5b7f373c-4d09-4fe1-8197-769c3cafd932"}]]],"subscribedEvents":[],"summary/status":{"coreAPIsummary":"http://34.159.217.74/demo-a-productcatalog/tmf-api/productCatalogManagement/v4 ","deployment_status":"In-Progress-CompCon","developerUIsummary":"http://34.159.217.74/demo-a-productcatalog/tmf-api/productCatalogManagement/v4/docs http://34.159.217.74/demo-a-productcatalog/tmf-api/partyRoleManagement/v4/docs ","managementAPIsummary":"","securityAPIsummary":"http://34.159.217.74/demo-a-productcatalog/tmf-api/partyRoleManagement/v4 "}}}
    meta.helm.sh/release-name: demo-a
    meta.helm.sh/release-namespace: components
  creationTimestamp: "2024-04-11T09:23:25Z"
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
  generation: 30
  labels:
    app.kubernetes.io/managed-by: Helm
    oda.tmforum.org/componentName: demo-a-productcatalog
  name: demo-a-productcatalog
  namespace: components
  resourceVersion: "36136187"
  uid: 3c9f4da9-4781-43a1-8071-d4ca7cb4d321
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      name: party
      specification: https://open-api.tmforum.org/TMF632-Party-v4.0.0.swagger.json
    exposedAPIs:
    - apitype: openapi
      developerUI: /demo-a-productcatalog/tmf-api/productCatalogManagement/v4/docs
      implementation: demo-a-prodcatapi
      name: productcatalogmanagement
      path: /demo-a-productcatalog/tmf-api/productCatalogManagement/v4
      port: 8080
      specification:
      - https://raw.githubusercontent.com/tmforum-apis/TMF620_ProductCatalog/master/TMF620-ProductCatalog-v4.0.0.swagger.json
  description: Simple Product Catalog ODA-Component from Open-API reference implementation.
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  functionalBlock: CoreCommerce
  id: TMFC001
  maintainers:
  - email: lester.thomas@vodafone.com
    name: Lester Thomas
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: demo-a-productcatalog-sm
      name: metrics
      path: /demo-a-productcatalog/metrics
      port: 4000
  name: ProductCatalogManagement
  owners:
  - email: lester.thomas@vodafone.com
    name: Lester Thomas
  publicationDate: "2023-08-18T00:00:00.000Z"
  securityFunction:
    componentVault:
      podSelector:
        name: demo-a-*
        namespace: components
        serviceaccount: default
      sideCar:
        port: 5000
      type: sideCar
    controllerRole: Admin
    exposedAPIs:
    - apitype: openapi
      developerUI: /demo-a-productcatalog/tmf-api/partyRoleManagement/v4/docs
      implementation: demo-a-partyroleapi
      name: partyrole
      path: /demo-a-productcatalog/tmf-api/partyRoleManagement/v4
      port: 8080
      specification:
      - https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
  status: specified
  version: 0.0.1
status:
  coreAPIs:
  - developerUI: http://34.159.217.74/demo-a-productcatalog/tmf-api/productCatalogManagement/v4/docs
    implementation: demo-a-prodcatapi
    ip: 34.159.217.74
    name: demo-a-productcatalog-productcatalogmanagement
    path: /demo-a-productcatalog/tmf-api/productCatalogManagement/v4
    port: 8080
    ready: true
    uid: 3be7df95-4f7a-45d6-a691-9147bacc644c
    url: http://34.159.217.74/demo-a-productcatalog/tmf-api/productCatalogManagement/v4
  kopf:
    progress: {}
  managementAPIs:
  - name: demo-a-productcatalog-metrics
    ready: false
    uid: b0481e80-1454-4c51-baba-8d846b5e4fee
  publishedEvents: []
  securityAPIs:
  - developerUI: http://34.159.217.74/demo-a-productcatalog/tmf-api/partyRoleManagement/v4/docs
    implementation: demo-a-partyroleapi
    ip: 34.159.217.74
    name: demo-a-productcatalog-partyrole
    path: /demo-a-productcatalog/tmf-api/partyRoleManagement/v4
    port: 8080
    uid: 5c04002e-55a0-4a66-9d41-109cee0cc714
    url: http://34.159.217.74/demo-a-productcatalog/tmf-api/partyRoleManagement/v4
  securityComponentVault:
  - - - name: demo-a-productcatalog
        ready: false
        uid: 5b7f373c-4d09-4fe1-8197-769c3cafd932
  subscribedEvents: []
  summary/status:
    coreAPIsummary: 'http://34.159.217.74/demo-a-productcatalog/tmf-api/productCatalogManagement/v4 '
    deployment_status: In-Progress-CompCon
    developerUIsummary: 'http://34.159.217.74/demo-a-productcatalog/tmf-api/productCatalogManagement/v4/docs
      http://34.159.217.74/demo-a-productcatalog/tmf-api/partyRoleManagement/v4/docs '
    managementAPIsummary: ""
    securityAPIsummary: 'http://34.159.217.74/demo-a-productcatalog/tmf-api/partyRoleManagement/v4 '
